seed: 0

train:
  steps: 1_000_000  # In number of environment steps
  tbptt_window: 30
  batch_size: 32
  log_interval: 30000 # In number of environment steps


model:
  vocab_size: 36
  hidden_dim: 512
  n_blocks: 4
  n_heads: 4
  ms_ratio: [1, 1]
  mlstm_kwargs: null
  penultimate_norm: True
  slstm_kwargs:
    use_conv: True

optimizer:
  learning_rate: 3e-4

env:
  name_length: 2
  val_length: 2
  name_vocab_size: 26
  val_vocab_size: 10
  max_vars: 4
  test_recall_prob: 0.5
  fill_before_recall: True